In [11]:
import os, sys, importlib
sys.path.append(os.path.abspath(".."))

import json
import pandas as pd

# my utils
from utils import extract_from_pdf
importlib.reload(extract_from_pdf)
from utils.extract_from_pdf import extract_text_from_pdf, extract_words_per_page

In [12]:
table=pd.read_csv("../results/table_clean.csv")
display(table.head())
table[['collection',"mss"]].value_counts(dropna=False)

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,NaN,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,NaN,2
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9

collection  mss
Additional  Add. 27879         14
Cotton      Caligula A. ii.    10
Royal       15. E. vi.          9
NaN         NaN                 7
Additional  Add. 4859.          7
                               ..
Royal       19. B. xiii.        1
            19. C. vii.         1
            19. C. viii.        1
            16. F. ix.          1
            16. F. v.           1
Name: count, Length: 394, dtype: int64

In [13]:
# table[(table['mss'].isna())|(table['ff'].isna())]
table[table[['mss',"ff"]].notna()]

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,NaN,NaN,NaN,NaN,NaN,NaN,16. C. xxiii.,ff. 2-69 b,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,16. C. iv. A. B.,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,16. D. iii. A. B.,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,Harley 5662.,ff. 1-56,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,Harley 3514,NaN,NaN
...,...,...,...,...,...,...,...,...,...
578,NaN,NaN,NaN,NaN,NaN,NaN,Add. 27879 f 239 b,NaN,NaN
579,NaN,NaN,NaN,NaN,NaN,NaN,Add. 28638,NaN,NaN
580,NaN,NaN,NaN,NaN,NaN,NaN,"Add. 29408, 29409",NaN,NaN
581,NaN,NaN,NaN,NaN,NaN,NaN,Add. 31042,"ff66 b-79 b, 82-94",NaN
582,NaN,NaN,NaN,NaN,NaN,NaN,Egerton 2515,ff. 3-141,NaN

In [14]:
table[table["collection"]=="Harley"]

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9
17,Dares Phrygius,Dares Phrygius,NaN,Classical Romances,Cycle of Troy,Harley,Harley 641.,ff. 1-8,12
25,Roman de Troie,Roman de Troie,Benoît de Sainte-More,Classical Romances,Cycle of Troy,Harley,Harley 4482,NaN,35
31,Historia Trojana,Historia Trojana,Guido delle Colonne,Classical Romances,Cycle of Troy,Harley,Harley 51.,ff. 3-105 b,40
...,...,...,...,...,...,...,...,...,...
518,NaN,Prophecy of Thomas of Erceldoune,NaN,NaN,NaN,Harley,Harley 2253.,"ff. 127, col. 2",328
519,NaN,Letter of Dindimus to Alexander the Great,NaN,NaN,NaN,Harley,Harley 2488.,ff. 114-117 b,139
522,NaN,L'Ordène de Chevalerie,NaN,NaN,NaN,Harley,Harley 4333.,ff. 115-117 b,810
523,NaN,Richard Cœur-de-Lion,NaN,NaN,NaN,Harley,Harley 4690.,ff. 106-115,949
524,NaN,Prophecies taken from Geoffrey of Monmouth and...,NaN,NaN,NaN,Harley,Harley 6148.,ff. 86-98 b,311

In [15]:
name_mss="Harley 3514"
mss=table[table["mss"]==name_mss]
display(mss)

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9

In [16]:
lines=extract_text_from_pdf(path_pdf="../data\catalogue_of_romance_vol1.pdf",
                            start_page=35, end_page=36)

----------------------------------------------page 35-----------------------------------------------
CLASSICAL EOMANCBS— TBOY. 11
The history is headed, in red : '* D itis creteDsis liber primus
incipit."
It begins : ** [ C]vncti reges qui Minois loue geniti pronepotes
gr^i§ imperitabiuit.'* And ends : " Senior iam prouecteque §tatis :
neque tamen inualidus uirium."
Colophon (which is worm-eaten, in parts): '^Deo Gratias.
Septimini de bello Troiano Sextus et ultimus liber feliciter explicit.
Per me lacobum de Trauersagnis, die decima mensis Marcij ad
honorem dei genitricisque matris [eijus [to]tiusque triumphantis
curi§ c^lestis. Amen."
The present copy substantially agrees with the printed
editions.
Harley 3514.
Vellum; xvth cent. Octavo; ff. 102, having 23 lines to a page. With
seven illuminated initials, and a space left for one which is not filled in ;
and with two borders at f[l 1, 2 . Written in an Italian hand. At the top of
f. 1 is the name of an owner, " Joannis Gaddi/' written in the 17th cent.
DiOTYB Cbetensis : the history of the Trojan War. In six
books. With prologue. Latin.
a. The prologuoi headed, *' D ithys Gretensis '* : in which it is
stated that the present history was discovered in the tomb of
Dictys atGnossus, written in Phoenician characters, and was turned
by Nero's orders into Greek, f. 1.
Begins : '^ D icthys Gretensis genere Gnoeo ciuitate Hisdem
temporibns quibus et Atride fuit peritus uocis ac litteris Phoenicum."
Ends : " Quorum seriem qui sequitur textus ostendit"
Printed in some of the ancient and all the modem editions
of Dictys. See that of Dederich, Bonn, 1833, pp. 6-9, and that
in Valpy's Glassies, London, 1825, pp. 15-17. The letter from
L. Septimius (or Septiminus), the asserted Latin translator, to
Q. Aradius, which is in most of the printed editions, is not here.
b. The history; with title, in red: "H§c sunt dithis ephe-
meridos belli troyani liber sextus incipit L[ucii] Septimini
translatoris." f. 2.
Begins: " Cvncti reges qui Minois loue geniti." Ends:
''Senior iam prouecte etatis, neque tamen inualidus uirium."

In [ ]:
from rapidfuzz import process, fuzz
mss_ff_s = ''.join(mss[['mss','ff']].iloc[0].dropna().astype(str))

result=process.extractOne(
    mss_ff_s, 
    lines,
    scorer=fuzz.ratio,
    score_cutoff=70
)
print(result[0])


idx_result=lines.index(result[0])
print(idx_result)

next_n_lines=2
notice=" ".join(lines[idx_result+1:idx_result+1+next_n_lines])
print('notice:', notice)

Harley 3514.
13
notice: Vellum; xvth cent. Octavo; ff. 102, having 23 lines to a page. With seven illuminated initials, and a space left for one which is not filled in ;

In [103]:
# material, cent, size, nb_pages, lines_per_page
import re
from rapidfuzz import process, fuzz

# notice_clean='.'.join(notice.split('.')[:3])
# print(notice_clean)
notice="Vellum; xvth cent. Octavo; ff. 102, having 23 lines to a page"
notice="Vellum;  early  xiiith  cent  Folio;  ffi  11,  in  double  columns,  haying  37 lines  to  a  colunm. "
# notice="Vellum; early  xmth  cent. Octavo; ff.  9,  having  38  lines  to  a  page."
# notice="Yellum ;  late  xmth  or  early  xivth  cent Octavo ;  ff.  18,  having  29  lines to  a  page. With  two  initials  in  blue  and  red."
# notice="Paper;  aj).  1801.  Small  Quarto; ff.  58,  haying  15  lines  to  a  paga. The  writer  has  used  the  Greek  d  to  represent  the  Welsh  dd,"
# notice="Yelltun ;  about  a.d.  1350.  Folio ;  £f.  77»  in  double  columns,  each  column containing  46  lines."
notice="Velltiin;  about  a.i>.  1B50:  Large  Folio;  ff.  58,  in  double  columnB,  each column  containing  58  lines. "
def eliminate_ponc(s):
    clean_s=re.sub(r'[^\w\s]','',s)
    clean_s=clean_s.strip()
    return clean_s



def get_el_by_fuzzy_research(list_research, contexts, cutoff=70):
    for r in list_research:
        el_contains=[c for c in contexts if r in c]
        if el_contains :
            el=el_contains[0].strip()
            return r, el
        
        #若没有匹配，进行模糊搜索：
        result=process.extractOne(
            r, 
            contexts,
            scorer=fuzz.ratio,
            score_cutoff=cutoff
        )

        if result:            
            # print(result[0])
            idx_result=contexts.index(result[0])
            el=contexts[idx_result].strip()
            # print(f"fuzzy result:{result[0]}")
            
            return result[0],el
        else:
            # print(f"no match for '{r}'!")
            return None, None


def get_notice_info(notice):
    #---init---
    material,cent, size, nb_page, nb_col, lines_per_page=None, None, None, None, None, None
        
    notice_el=notice.split(";")
    # print(notice_el)
    
    # #---materia---
    material=notice_el[0]
    # print(f"material: {material}")


    # #---cent & size---   
    if 'cent' in notice_el[1]:#如果有cent，按cent切分
        cent=eliminate_ponc(notice_el[1].split("cent")[0])
        size=eliminate_ponc(notice_el[1].split("cent")[1])
    
    else: # 没有则找大写切分呢
        first_upper_idx = next((i for i, c in enumerate(notice_el[1]) if c.isupper()), None)
        if first_upper_idx:# 若有大写
            # print(f"first_upper_idx:{first_upper_idx}; first supper :{notice_el[1][first_upper_idx]}")
            cent=eliminate_ponc(notice_el[1][:first_upper_idx])
            size=eliminate_ponc(notice_el[1][first_upper_idx:])
  
    print(f"century:{cent}")
    print(f"size: {size}")
    print("\n")
    
    
    # # ---ff---
    ff_el=notice_el[2].split(",")
    # print(f"contexts of 3e el of notice: {ff_el}")

    #取ff类似字样后的数字！    
    page_ff=ff_el[0].split()
    # print(page_ff)
    first_el_with_f=[_ for _ in page_ff if 'f' in _][0]
    idx_ff=page_ff.index(first_el_with_f)
    nb_page=eliminate_ponc(page_ff[idx_ff+1])
    # print('nb_page:',nb_page)
    
    
    # ff_match, page_ff=get_el_by_fuzzy_research(list_research=["ff","f."], contexts=ff_el, cutoff=70)
    # if page_ff:
    #     nb_page=[p for p in page_ff.split() if p.isdigit()][0]  
    #     print(nb_page)
        
    # else :
    #     print(f"no match for 'ff'!")
    
    
    col_match, columns=get_el_by_fuzzy_research(list_research=["columns"], contexts=ff_el, cutoff=70)
    if columns:
        columns_list=[eliminate_ponc(_) for _ in columns.split()]
        idx_col=columns_list.index(col_match)#取col前的一个词
        nb_col=columns_list[idx_col-1]
    
    
    lines_match, lines_per_page=get_el_by_fuzzy_research(list_research=["lines"], contexts=ff_el, cutoff=70)
    if lines_per_page:        
        lines_per_page_list=[eliminate_ponc(_) for _ in lines_per_page.split()]
        idx_lines=lines_per_page_list.index(lines_match)#取col前的一个词
        nb_lines=lines_per_page_list[idx_lines-1]
    
    # print(f"page: {nb_page}")
    # print(f"nb of columns: {nb_col}")
    # print(f"lines_per_page: {nb_lines}")
    
    info={"mateiral":material,
          "cent":cent,
          "size":size,
          "nb_page":nb_page,
          "nb_columns":nb_col,
          "lines_per_page":nb_lines
          }
    
    
    return info

print(notice,"\n")
notice_info=get_notice_info(notice)
print(notice_info)

Velltiin;  about  a.i>.  1B50:  Large  Folio;  ff.  58,  in  double  columnB,  each column  containing  58  lines.

century:about  ai  1
size: B50  Large  Folio


{'mateiral': 'Velltiin', 'cent': 'about  ai  1', 'size': 'B50  Large  Folio', 'nb_page': '58', 'nb_columns': None, 'lines_per_page': '58'}

In [ ]:
from rapidfuzz import process, fuzz

def get_mss_info(title_theme, index_table_clean, score_cutoff=70):

    # 1. EXACT match
    if title_theme in index_table_clean:
        title_index=title_theme
        return title_index, index_table_clean[title_theme]
    
    # 2. FUZZY match
    result = process.extractOne(
        title_theme,
        index_table_clean.keys(),
        scorer=fuzz.ratio,
        score_cutoff=score_cutoff
    )

    if result:
        best_match, score, _ = result
        title_index=best_match
        # print(f"Fuzzy match: {best_match} (score={score})")
        return title_index, index_table_clean[best_match]
    # print(f"[No match] found for {title}")
    
    return None, []